### PR TITLE
BST-2963: scan id label

### PR DESCRIPTION
**Pull request by JonathanSerafini**

### CODE REVIEW

**Review by fproulx-boostsecurity — APPROVED** [review]

**Comment by boost-infra-circleci** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/boostsecurityio/scanner?version=dev:8063796ead746781b811431220484636c3d57ee5

**Comment by boost-infra-circleci** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/boostsecurityio/scanner?version=dev:8063796ead746781b811431220484636c3d57ee5

**Comment by boost-infra-circleci** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/boostsecurityio/scanner?version=dev:8063796ead746781b811431220484636c3d57ee5

**Comment by boost-infra-circleci** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/boostsecurityio/scanner?version=dev:8063796ead746781b811431220484636c3d57ee5

**Pull request merged**
