### PR TITLE
resolve incorrect ci version being launched

### PR DESCRIPTION
**Pull request by JonathanSerafini**

### CODE REVIEW

**Comment by boost-infra-circleci** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/boostsecurityio/scanner?version=dev:67e676bfb1063e573216c94efbfa0625c8952405

**Review by Clearedkinkajou — APPROVED** [review]

**Comment by boost-infra-circleci** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/boostsecurityio/scanner?version=dev:a8bf4278f6d8938519f3b7611dfa1ad74b0d34cd

**Comment by boost-infra-circleci** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/boostsecurityio/scanner?version=dev:a8bf4278f6d8938519f3b7611dfa1ad74b0d34cd

**Comment by boost-infra-circleci** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/boostsecurityio/scanner?version=4.0.6

**Pull request merged**
